# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'baitap15' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'ObjectMapper'
pod 'GoogleAPIClientForREST/YouTube', '~> 1.2.1'
pod 'GoogleSignIn', '~> 4.0'

end
