platform :ios, '9.0'

target 'BaiTapAPI' do
  use_frameworks!

  # Pods for BaiTapAPI
  pod 'GoogleAPIClientForREST/YouTube', '~> 1.2.1'
  pod 'Google/SignIn', '~> 3.0.3'
  pod 'ObjectMapper', '~> 3.5'
end
